### PR TITLE
2025 04 02 fix tag bugs

### LINKED ISSUE #154: Bug Report: `tag` Command Reports Success When Adding Existing Tags
## Bug: `tag` Command Reports Success When Adding Existing Tags

**Main Issue:**
`tag` command incorrectly reports success when adding tags that already exist

**Description:**
When executing the `tag` command to add a tag that already exists on a patient, the system incorrectly reports success as if a new tag was added. This gives users false feedback that something has changed when in fact no changes were made to the patient's tags.

**Steps to Reproduce:**
1. Launch the application
2. Identify a patient (e.g., Alex Yeoh at index 1) who already has a specific tag (e.g., "friends")
3. Execute the command: `tag 1 t/friends`
4. Observe that the system reports "Tags [friends] successfully added to Alex Yeoh" despite no actual changes being made

**Expected Behavior:**
The system should either:
- Inform the user that the specified tag(s) already exist on the patient
- Only report success if actual changes were made to the patient's tags

**Actual Behavior:**
The system displays a success message "Tags [friends] successfully added to Alex Yeoh" even when attempting to add tags that already exist on the patient.

**Severity:**
Medium - This issue provides misleading feedback to users but doesn't cause data loss or prevent functionality.

**Suggested Fix:**
Modify the `tag` command implementation to:
1. Check if the specified tags already exist on the patient before attempting addition
2. Only display success messages when actual changes are made
3. Provide appropriate feedback when attempting to add existing tags, such as "Tag [friends] already exists on Alex Yeoh"

**Screenshot:**
Image

### PR DESCRIPTION
**Pull request by Bryce-3D**
(1) Closes #154

### CODE REVIEW

**Comment by Bryce-3D** [comment]
TODO: Close #147

**Comment by Bryce-3D** [comment]
TODO: Close #156

**Comment by Bryce-3D** [comment]
*#158 is the same as #154, so this also closes #158

File: src/main/java/seedu/address/logic/commands/TagCommand.java [hunk 1]
```diff
@@ -33,6 +33,8 @@ public class TagCommand extends Command {
     public static final String EMPTY_TAG_ERROR = "Tag must be non-empty."
             + '\n'
             + "Example: " + COMMAND_WORD + " 2 t/Diabetes";
+    public static final String REPEATED_TAG_ERROR =
+            "Tag %1$s was inputted multiple times";
```
Comment (Eun777) [inline src/main/java/seedu/address/logic/commands/TagCommand.java:37]: Would it be better to have it as `"Tag [%1$s] was inputted multiple times"` instead for greater clarity?

**Review by Eun777 — CHANGES_REQUESTED** [review]
Minor change recommended for phrasing to be cohesive with the rest of the messages. Other than that, looks good to me!

File: src/main/java/seedu/address/logic/commands/TagCommand.java (hunk 1 above)
Comment (szelingtan) [reply src/main/java/seedu/address/logic/commands/TagCommand.java:37]: Might be good to add more tests for the codecov too!

Comment (Bryce-3D) [reply src/main/java/seedu/address/logic/commands/TagCommand.java]: Brackets added now, and some tests added
