### PR TITLE
Bug Fix: `add` command mandates last visit

### LINKED ISSUE #142: `add` command fails (does not display command or do anything) when the `d/` prefix is missing
Image

The `add` command fails (does not display error message or do anything) when the input is missing the `d/` prefix

**Documentation Reference (User Guide)**
### Adding a patient: `add`

Adds a patient to the patient contact book.

Format: `add n/NAME p/PHONE_NUMBER e/EMAIL a/ADDRESS d/LAST_VISIT_DATE [t/TAG]…​`

<div markdown="span" class="alert alert-primary">:bulb: **Tip:**
A patient can have any number of tags (including 0)
</div>

Examples:
* `add n/John Doe p/98765432 e/johnd@example.com a/John street, block 123, #01-01 d/2025-01-12`
* `add n/James Ho p/98280482 e/jamesho@example.com a/123, Clementi Rd, 1234665 d/2025-01-25 t/diabetes`

## Expected behaviour
Either:
- An error message should be shown to the user, informing them that the `d/` prefix (for initialising lastVisit) is missing. The documentation also shows the `d/` prefix as a compulsory prefix.

## Actual behaviour
An error message should be shown to the user, informing them that the `d/` prefix (for initialising lastVisit) is missing.

## Suggested changes
While a simple fix would be to add the error message, **I recommend reworking the `add` command to make the lastVisit field optional.**

## Severity
High - This issue results in breaking functionality, and severely affects the user experience.

### LINKED ISSUE #143: `add` command's error message when `d/` date is invalid is not informative enough
Image

Minor issue:

When an invalid date is provided in the for the lastVisit field via the `d/` prefix (like `2025-12-12` - This date is in the future), the error message displayed is not informative enough. 

Error message displayed: `Last visit must take in a valid date of format YYYY-MM-DD`

Suggested changes:
Make the error message more descriptive: explicitly mention that the date cannot be in the future.

### PR DESCRIPTION
**Pull request by Eun777**
- Fix bug where `add` command mandates last visit
Closes #142 
Closes #143

### CODE REVIEW

File: src/main/java/seedu/address/model/util/SampleDataUtil.java [hunk 1]
```diff
@@ -21,30 +21,43 @@
  * Contains utility methods for populating {@code AddressBook} with sample data.
  */
 public class SampleDataUtil {
-    public static final LastVisit EMPTY_LAST_VISIT = new LastVisit(LocalDate.parse("1111-11-11"));
+    public static final LastVisit EMPTY_LAST_VISIT = new LastVisit(LocalDate.parse("2025-03-01"));
```
Comment (Bryce-3D) [inline src/main/java/seedu/address/model/util/SampleDataUtil.java:24]: Hi! Same comment as this one from #178

image

**Comment by Bryce-3D** [comment]
Looks good to me~
