### PR TITLE
Force at least 1 tag in tag cmd

### LINKED ISSUE #152: Bug Report: `tag` Command Allows Empty Tag Parameters
# Bug Report: `tag` Command Allows Empty Tag Parameters

**Main Issue:**
`tag` command accepts empty tag parameters and reports success incorrectly

**Description:**
When executing the `tag` command without specifying any tag parameters (e.g., `tag 1`), the system incorrectly reports success ("Tags successfully added to Alex Yeoh") despite the command format requiring at least one optional tag field to be provided. According to the documentation, "at least one of the optional fields must be provided" for the command to be valid.

**Steps to Reproduce:**
1. Launch the application
2. Ensure there is at least 1 patient in the list (Alex Yeoh at index 1)
3. Execute the command: `tag 1` (without any tag parameters)
4. Observe the output message: "Tags successfully added to Alex Yeoh"

**Expected Behavior:**
The system should reject the command and display an error message indicating that at least one tag parameter must be provided, such as "Invalid command format! Please provide at least one tag to add."

**Actual Behavior:**
The system accepts the command and displays: "Tags successfully added to Alex Yeoh" even though no tags were specified for addition. Note the empty space after "Tags" in the message, indicating that no tags were actually processed.

**Documentation Reference:**
According to the command documentation:
* "At least one of the optional fields must be provided."
* The correct format is `tag INDEX [t/TAG]…` where at least one tag must be specified.
* Only `t/` without any tags is specifically documented as a special case to remove all tags.

**Severity:**
Medium - The command executes incorrectly, violating the specified requirements, which could lead to user confusion and unintended behavior.

**Suggested Fix:**
Modify the command parser to validate that at least one tag parameter is provided (e.g., `tag 1 t/diabetes`). If no tags are provided, the system should display an appropriate error message.

**Additional Notes:**
This behavior contradicts the documentation requirements and creates confusion about what action, if any, is actually being performed when the command is executed in this invalid format. The empty space in "Tags successfully added" further suggests a bug in the command handling.

**Screenshot:**
Image

### PR DESCRIPTION
**Pull request by Bryce-3D**
Closes #152

### CODE REVIEW

**Review by Eun777 — CHANGES_REQUESTED** [review]
The rest looks good to me! Minor change in phrasing could be clearer.

File: src/main/java/seedu/address/logic/commands/TagCommand.java [hunk 1]
```diff
@@ -26,6 +26,10 @@ public class TagCommand extends Command {
             + '\n'
             + "Example: " + COMMAND_WORD + "39 t/High Blood Pressure "
             + "t/Seafood Allergy";
+    public static final String PLS_USE_AT_LEAST_ONE_TAG =
```
Comment (Eun777) [inline src/main/java/seedu/address/logic/commands/TagCommand.java:29]: Would it be better to name as `NO_TAG_INCLUDED_ERROR`?

**Review by Eun777 — CHANGES_REQUESTED** [review]
The rest looks good to me, just minor change with variable naming suggested.

**Comment by Eun777** [comment]
Looks good to me!

**Comment by Eun777** [comment]
Looks good to me!
