### PR TITLE
Bug Fix: `delLastVisit` reports delete success when lastVisit is empty

### LINKED ISSUE #140: `delLastVisit` Does Not Notify If The Patient Already Had No Last Visit Date
# Suggestion - `delLastVisit` should notify if the specified patient does not have any last visit date

Currently, the command just says that it has been deleted successfully despite nothing changing. This might make someone input a wrong index and not realize that they selected someone else who didn't have a last visit saved.

Steps to reproduce:
- Have at least one patient in CareConnect, where the first patient has no last visit date
- Run `delLastVisit 1`

Expected: Some message saying that patient 1 does not have any last visit info to delete

Actual: Last visit date successfully deleted from Homura

Image

Image

### LINKED ISSUE #171: Bug Report: Last visit date is set to 1111-11-11 in sample
**Main Issue:**
Sample data uses unrealistic Last visit date value (1111-11-11), which may confuse users or make the app appear buggy.

**Description:**
When launching the app for the first time, the sample patient records are pre-filled with a Last visit of 1111-11-11. While this is just sample data, the date appears strange and can give users the wrong impression (e.g., that there's a bug or incorrect parsing logic).

**Steps to Reproduce:**
1. Launch the application for the first time or delete the addressbook.json file.
2. View the patient list
3. Notice all patients have "Last visit: 1111-11-11"

**Expected Behavior:**
Sample data should use realistic values to simulate real-world use. E.g.:
1. Use plausible past dates like 2023-10-15
2. Or leave Last visit empty for some patients to showcase optionality

**Actual Behaviour:**
All patients in the sample data have the same unrealistic date (1111-11-11), which stands out as unnatural.

**Severity:**
Low - No impact on functionality, but affects first impressions and user confidence.

**Suggested Fix:**
Update SampleDataUtil.java (or wherever it's stored) to use more natural dates or vary them for realism.

**Screenshot:**
Image

### LINKED ISSUE #172: Bug Report: `delLastVisit` reports delete success when last visit field is empty
**Main Issue:**
`delLastVisit`  command reports successful deletion even when the Last visit field was already empty.

**Description:**
When running `delLastVisit` on a patient with no recorded last visit, the system still responds with a success message. This is misleading, since there was nothing to delete in the first place.

**Steps to Reproduce:**
1. Launch the application
2. Run the command: `delLastVisit 1`
3. Run the command: `delLastVisit 1`
4. Observe the success message (e.g. "Last visit date successfully deleted from Alex Yeoh")

**Expected Behavior:**
The system should check if a last visit exists before attempting deletion. If the field is empty, it should respond with something like:
"No last visit to delete for patient: Alex Yeoh."

**Actual Behaviour:**
System always shows a success message, regardless of whether there was a last visit date to delete.

**Severity:**
Low - This issue could lead to inaccurate feedback and may confuse users.

**Suggested Fix:**
1. Add a check before performing deletion
2. Display a different message if the field is already empty

**Screenshot:**
Image

### PR DESCRIPTION
**Pull request by Eun777**
- Fix bug where `delLastVisit` reports delete success when lastVisit is empty
- Update sample patient list to suit CareConnect
Closes #140 
Closes #171 
Closes #172

### CODE REVIEW

File: src/main/java/seedu/address/model/util/SampleDataUtil.java [hunk 1]
```diff
@@ -21,30 +21,43 @@
  * Contains utility methods for populating {@code AddressBook} with sample data.
  */
 public class SampleDataUtil {
-    public static final LastVisit EMPTY_LAST_VISIT = new LastVisit(LocalDate.parse("1111-11-11"));
+    public static final LastVisit EMPTY_LAST_VISIT = new LastVisit(LocalDate.parse("2025-03-01"));
```
Comment (Bryce-3D) [inline src/main/java/seedu/address/model/util/SampleDataUtil.java:24]: Hi! Would this be better named `DEFAULT_LAST_VISIT` rather than `EMPTY_LAST_VISIT`?

**Comment by Bryce-3D** [comment]
Looks good to me~
