### PR TITLE
Fix codestyle in `DelLastVisitCommand.java`

### LINKED ISSUE #90: Fix codestyle in `DelLastVisitCommand.java`
Noticed some iffy codestyle while working on something else

### PR DESCRIPTION
**Pull request by Bryce-3D**
Closes #90

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/DelLastVisitCommand.java [hunk 1]
```diff
@@ -62,15 +61,14 @@ public CommandResult execute(Model model) throws CommandException {
...
 
-        // Create new Patient with NA last visit
+        // Create a new Patient with `null` last visit
         Patient patientToEdit = lastShownList.get(index.getZeroBased());
         Patient editedPatient = new Patient(
                 patientToEdit.getName(),
                 patientToEdit.getPhone(),
                 patientToEdit.getEmail(),
                 patientToEdit.getAddress(),
                 null,
```
Comment (Luoq1-Xu) [inline src/main/java/seedu/address/logic/commands/DelLastVisitCommand.java:71]: Need to be really careful with this, may cause problems later on. (Having null in the lastVisit field instead of a LastVisit object)

File: src/main/java/seedu/address/logic/commands/DelLastVisitCommand.java [hunk 2]
```diff
@@ -42,7 +41,7 @@ public DelLastVisitCommand(Index ind) {
      * @param patient The newly modified patient.
      * @return The msg to send upon successful deletion.
      */
-    public String generateSuccessMessage(Patient patient) {
+    private String generateSuccessMessage(Patient patient) {
```
Comment (szelingtan) [inline src/main/java/seedu/address/logic/commands/DelLastVisitCommand.java:44]: good use of information hiding

File: src/main/java/seedu/address/logic/commands/DelLastVisitCommand.java [hunk 3]
```diff
@@ -23,17 +23,16 @@ public class DelLastVisitCommand extends Command {
...
     /**
      * Creates a {@code DelLastVisitCommand}.
      *
-     * @param ind The index of the patient to modify.
+     * @param index The index of the patient to modify.
      */
-    public DelLastVisitCommand(Index ind) {
-        index = ind;
+    public DelLastVisitCommand(Index index) {
+        this.index = index;
```
Comment (szelingtan) [inline src/main/java/seedu/address/logic/commands/DelLastVisitCommand.java:35]: good choice of renaming the variable from ind to index

File: src/main/java/seedu/address/logic/commands/DelLastVisitCommand.java (hunk 1 above)
Comment (Bryce-3D) [reply src/main/java/seedu/address/logic/commands/DelLastVisitCommand.java:71]: Any suggestions on how I could make it not use `null` instead?

Comment (Eun777) [reply src/main/java/seedu/address/logic/commands/DelLastVisitCommand.java:71]: Maybe can create an empty last visit class or variable to be used for this?

**Review by Eun777 — COMMENTED** [review]
The rest looks good to me, good work.
